### ISSUE TITLE
Force Close: Loading League List

### ISSUE THREAD

**Issue by midnight-sun** [josephroqueca/bowling-companion#228]
I have recently experienced force close, when I pick the bowler, and the app displays the league/event list.  It force closes almost immediately.  

I have not reliably been able to reproduce the error.  It seems to continue after multiple re-opens/clearing all active apps etc, only to start working 10 minutes later.

I'm not entirely clear about the android "feedback" system so I do not know if you are getting the one or two reports I have sent your way. 

If I happen across it again, or can produce the effect reliably I will post it here.

First time it happened I was idle and just wanted to check my stats.
Second time it happened at the end of game 2 (frame 8) of a 3 game series.  I was able to reopen the app and continue scoring around frame 2 of game 3.

Steve

EDIT: I noticed that the changelog updated from a few minutes ago lists a "fix when returning the app from the background", this may be related to the bug.

**Comment by josephroqueca** [comment]
Hi @midnight-sun, I just wanted to say I did see your previous issue and have added an option to share your games: https://github.com/josephroqueca/bowling-companion/issues/186

I'll take a look into this for the next release, if it hasn't been fixed.

**Comment by josephroqueca** [comment]
Hi @midnight-sun have you noticed if this issue is still occurring? I'm not seeing any errors being logged that would indicate this behaviour, so I'm wondering if it was perhaps fixed?
I've got a release coming out very soon that will also fix a large number of other bugs. I'm going to close this issue for now, and if you find that the issue still occurs after the next update, comment here and I'll investigate further and re-open the issue.
